# This default configuration file is designed for 32 GB of RAM
# Configuration file for ZRAM devices
# Format: SIZE | COMPRESSION_ALGORITHM | TYPE (swap|tmp|mount) | TARGET_PATH_OR_LABEL

16G | zstd | swap  | zswap
1G  | zstd | tmp   | /tmp
22G | zstd | mount | /var/tmp/portage
